apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-deployment
  labels:
    app: helios-proof
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios-proof
  template:
    metadata:
      labels:
        app: helios-proof
    spec:
      containers:
        - name: helios-container
          image: testacr1245.azurecr.io/helios-proof:latest   # 👈 Replace with your ACR image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: dockerhub-secret  # 👈 Created via kubectl (see below)

---

apiVersion: v1
kind: Service
metadata:
  name: helios-service
  labels:
    app: helios-proof
spec:
  type: LoadBalancer  # 👈 Use ClusterIP if you only want internal access
  selector:
    app: helios-proof
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: helios-config
data:
  APP_NAME: "Helios Proof"
  ENVIRONMENT: "production"
